version: "2.4"
services:
  backend-api:
    build: ./backend-api
    env_file:
      - env.example
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ci

  postgres:
    image: postgres:12-alpine
    env_file:
      - env.example
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10
    networks:
      - ci

networks:
  ci:
